const $=s=>document.querySelector(s), avatars=['🦖','👽','🦆','🧑‍🚀','🐸','🗿'],names=['失業恐龍','路過外星人','下班鴨','宇宙烤手','躺平蛙','沉默石像'];
const foods={corn:['🌽','玉米',14],beef:['🥩','牛肉',9],wing:['🍗','雞翅',18],mushroom:['🍄','杏鮑菇',12]};
let avatar=avatars[0],me=null,state=null,events=null,selected=null,sound=false,audio,toastTimer;
let danmakuOn=true,chatReady=false,lastChatId='',lane=0;
const seenChat=new Set();
function fly(message){if(!danmakuOn||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const area=$('#danmaku');if(area.children.length>=12)return;const el=document.createElement('span');el.className='danmaku-message'+(message.playerId===me?.id?' mine':'');el.textContent=message.avatar+' '+message.name+'：'+message.text;el.style.top=(lane++%5)*17+'%';el.style.setProperty('--travel',area.clientWidth+'px');area.append(el);el.addEventListener('animationend',()=>el.remove());setTimeout(()=>el.remove(),13000)}
function renderChat(){const messages=state.chat||[];$('#chatCount').textContent=state.players.length+'/5';const newest=messages.at(-1)?.id;if(newest&&newest!==lastChatId){const area=$('#chatMessages'),atBottom=area.scrollHeight-area.scrollTop-area.clientHeight<70;for(const message of messages){if(seenChat.has(message.id))continue;if(!lastChatId)area.replaceChildren();const row=document.createElement('div');row.className='message'+(message.playerId===me?.id?' mine':'');row.innerHTML=`<span class="message-avatar">${esc(message.avatar)}</span><div class="message-content"><div class="message-meta"><span>${esc(message.name)}</span><time>${new Date(message.time).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}</time></div><div class="message-text">${esc(message.text)}</div></div>`;area.append(row);if(chatReady)fly(message);seenChat.add(message.id);lastChatId=message.id}while(area.children.length>50)area.firstChild.remove();if(atBottom||messages.at(-1)?.playerId===me?.id)area.scrollTop=area.scrollHeight;const ids=new Set(messages.map(m=>m.id));for(const id of seenChat)if(!ids.has(id))seenChat.delete(id)}chatReady=true}
function html(selector,value){const el=$(selector);if(el.innerHTML!==value)el.innerHTML=value}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
async function api(path,data){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(me?{Authorization:'Bearer '+me.token}:{})},body:JSON.stringify(data)});const b=await r.json();if(!r.ok){if(r.status===401){events?.close();me=null;$('#joinDialog').showModal()}throw Error(b.error)}return b}
function beep(){if(!sound)return;audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=220+Math.random()*500;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.12)}
async function action(data){if(!me){$('#joinDialog').showModal();return}try{await api('action',data);beep()}catch(e){toast(e.message)}}
function condition(f){return Math.max(...f.sides)>145?'burnt':Math.min(...f.sides)>=65?'ready':'raw'}
function label(f){return {burnt:'炭化藝術',ready:'開吃！',raw:'還在烤'}[condition(f)]}
function render(){
 renderChat();
 $('#roomLabel').textContent=`炭火 ${state.id} 號桌 · ${state.players.length} / 5 人`;
 html('#seats',Array.from({length:5},(_,i)=>{const p=state.players.find(x=>x.seat===i);return p?`<div class="seat ${p.id===me?.id?'me':''}">${p.bubble?`<div class="bubble">${esc(p.bubble)}</div>`:''}<div class="avatar">${p.avatar}</div><div class="seat-name">${esc(p.name)}${p.id===me?.id?' · 你':''}</div><small>已吃 ${p.eaten} 口空氣</small></div>`:`<div class="seat empty"><div class="avatar">＋</div><div class="seat-name">留個位子</div><small>等一個餓的人</small></div>`}).join(''));
 html('#grill',Array.from({length:9},(_,i)=>{const f=state.food.find(x=>x.slot===i);return f?`<button class="food-slot ${condition(f)}" data-food-id="${f.id}" aria-label="${foods[f.kind][1]}，${label(f)}，點擊操作">${foods[f.kind][0]}<small>${label(f)}</small></button>`:'<div class="food-slot empty"></div>'}).join(''));
 $('#heat').textContent=`🔥 ${Math.round(state.heat*100)}%`;$('#event').textContent=state.event;$('#feed').innerHTML=state.log.map(l=>`<li>${esc(l.text)}</li>`).join('');
 if(selected){const f=state.food.find(f=>f.id===selected);if(f){$('#foodTitle').textContent=foods[f.kind][0]+' '+foods[f.kind][1];$('#foodState').textContent=`${f.owner} 放的 · ${label(f)}。A 面 ${Math.round(f.sides[0])}% / B 面 ${Math.round(f.sides[1])}%（目前烤 ${f.side===0?'A':'B'} 面）。兩面 65% 可吃，超過 145% 烤焦。`}else{$('#foodDialog').close();selected=null;toast('這口已經被吃掉了。')}}
}
$('#avatars').innerHTML=avatars.map((a,i)=>`<button type="button" data-avatar="${a}" aria-label="${names[i]}" aria-pressed="${i===0}">${a}</button>`).join('');
$('#avatars').onclick=e=>{const b=e.target.closest('button');if(!b)return;avatar=b.dataset.avatar;$('#avatars').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b))};
$('#menu').innerHTML=Object.entries(foods).map(([k,[emoji,name,sec]])=>`<button data-add="${k}"><b>${emoji}</b><span>${name}<small>每面約 ${sec} 秒</small></span></button>`).join('');
$('#menu').onclick=e=>{const b=e.target.closest('[data-add]');if(b)action({type:'add',food:b.dataset.add})};
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action({type:b.dataset.action}));
$('#say').onchange=e=>{if(e.target.value!=='')action({type:'say',index:Number(e.target.value)});e.target.value=''};
$('#grill').onclick=e=>{const b=e.target.closest('[data-food-id]');if(b){selected=b.dataset.foodId;render();$('#foodDialog').showModal()}};
$('#flip').onclick=()=>action({type:'flip',id:selected});$('#eat').onclick=()=>{action({type:'eat',id:selected});selected=null;$('#foodDialog').close()};$('#closeFood').onclick=()=>{selected=null;$('#foodDialog').close()};$('#foodDialog').onclose=()=>{selected=null};
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='♫ 音效 '+(sound?'開':'關');$('#sound').setAttribute('aria-pressed',sound);beep()};
$('#danmakuToggle').onclick=()=>{danmakuOn=!danmakuOn;$('#danmakuToggle').textContent='彈幕 '+(danmakuOn?'開':'關');$('#danmakuToggle').setAttribute('aria-pressed',danmakuOn);if(!danmakuOn)$('#danmaku').replaceChildren()};
$('#chatInput').oninput=()=>{$('#chatLength').textContent=$('#chatInput').value.length+' / 100'};
$('#chatForm').onsubmit=async e=>{e.preventDefault();if(!me){$('#joinDialog').showModal();return}const input=$('#chatInput'),text=input.value.trim(),button=$('#chatForm button');if(!text)return;button.disabled=true;try{await api('action',{type:'chat',text});input.value='';$('#chatLength').textContent='0 / 100';input.focus()}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#invite').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('連結已複製，叫朋友帶著空氣來！')}catch{toast('請複製網址列連結邀請朋友。')}};
$('#leave').onclick=async()=>{try{await api('leave',{});sessionStorage.removeItem('bbq');location.href='/'}catch(e){toast(e.message)}};
function connect(){events?.close();chatReady=false;events=new EventSource('/api/events?token='+encodeURIComponent(me.token));events.onmessage=e=>{state=JSON.parse(e.data);$('#connection').textContent='● 炭火連線中';render()};events.onerror=()=>{$('#connection').textContent='正在重新生火…';if(events.readyState===EventSource.CLOSED){events.close();sessionStorage.removeItem('bbq');me=null;$('#joinError').textContent='座位已釋出，請重新入座。';$('#joinDialog').showModal()}}}
$('#joinForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('#joinError').textContent='';try{let token;try{token=JSON.parse(sessionStorage.getItem('bbq'))?.token}catch{}me=await api('join',{name:$('#name').value,avatar,room:new URLSearchParams(location.search).get('room'),token});sessionStorage.setItem('bbq',JSON.stringify(me));history.replaceState({},'', '?room='+me.room);$('#joinDialog').close();$('#invite').hidden=false;$('#leave').hidden=false;connect()}catch(e){$('#joinError').textContent=e.message;$('#newRoom').hidden=false}finally{b.disabled=false}};
$('#joinDialog').addEventListener('cancel',e=>{if(!me)e.preventDefault()});
state={players:[],food:[],log:[],heat:1,event:'☾ 今晚的熱量，只存在於想像。'};render();$('#roomLabel').textContent='今晚，誰來顧火？';$('#joinDialog').showModal();

