import {test,after} from 'node:test';import assert from 'node:assert/strict';
process.env.BBQ_MAX_PLAYERS='3';process.env.BBQ_MAX_ROOMS='1';process.env.BBQ_DB_PATH=':memory:';
const {server}=await import('./server.js?capacity-test');
delete process.env.BBQ_MAX_PLAYERS;delete process.env.BBQ_MAX_ROOMS;
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
after(()=>{server.closeAllConnections();server.close()});
async function post(path,body,token){const r=await fetch(base+'/api/'+path,{method:'POST',headers:{'content-type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};}
test('full site rejects new visitors, admits existing sessions, and frees capacity on leave',async()=>{const people=[];for(let i=0;i<3;i++){const r=await post('join',{name:'象'+i,room:'CAP88'});assert.equal(r.status,200);people.push(r.data)}assert.equal((await post('join',{name:'滿了',room:'CAP88'})).status,503);assert.equal((await post('join',{name:'恢復',token:people[0].token})).status,200);assert.equal((await post('action',{type:'fan'},people[0].token)).status,200);await post('leave',{},people[1].token);assert.equal((await post('join',{name:'新房',room:'NEW88'})).status,503);const newcomer=await post('join',{name:'新客',room:'CAP88'});assert.equal(newcomer.status,200);for(const p of [...people,newcomer.data])await post('leave',{},p.token);const fresh=await post('join',{name:'新桌',room:'NEW88'});assert.equal(fresh.status,200);await post('leave',{},fresh.data.token);});
test('private files are never public and malformed JSON bodies fail cleanly',async()=>{for(const path of ['/data/expulsions.sqlite','/.env','/expulsion-store.js','/server.js'])assert.equal((await fetch(base+path)).status,404);assert.equal((await post('join',null)).status,400);assert.equal((await fetch(base+'/privacy')).status,200);assert.equal((await fetch(base+'/third-party-notices.txt')).status,200);});
